### ISSUE TITLE
Use child apps (or other means) to launch News, Chart & Watchlist

### ISSUE THREAD

**Issue by jrhenderson1988** [ScottLogic/StockFlux#1262]
Still needs to support receiving intents and if possible try to raise intent first and fall back to this approach. The current OpenFin FDC3 does not seem to properly support intents so we need this fallback to make sure our apps continue to work. Create a react hook for whichever approach we take, eventually create PR for OpenFin React Hooks.

**Comment by AugusteBa** [comment]
I think this #1250 refers to the same issue.
