### ISSUE TITLE
Todo app

### ISSUE THREAD

**Issue by jrhenderson1988** [ScottLogic/StockFlux#1267]
Create a basic, traditional todo app using React and OpenFin. To begin with, the app should be fairly basic and should:
- Allow user to create todo items
- Allow user to remove todo items
- Allow users to mark todo items as complete/incomplete
- Use OpenFin's notifications SDK to create toasts when users create, update or remove todo items
- Local storage should be used to store items initially

---

### MVP

- Use local storage to store items
- Same size as news app (400x400)
- Responsive (UI should stretch to fit width, item container should stretch to allow more items when resized vertically)
- Clicking item should expand to show all text
- Items that are too long should be truncated (show ellipsis)

#### Goals:
- Add a todo item (Notification should happen)
- Update a todo item (Notification should happen)
- Remove a todo item (Notification should happen)
- Re-ordering items (Drag and drop)
- Mark items as complete (Notification should happen)
- Filter by complete/active

#### Stretch:
- Sort by most recently created and updated
- Multiple lists

Initial data structure:

```
  [
    {
      text: "Something to do",
      completed: false,
      created: new Date()
    }
  ]
```

#### Future

To be discussed and agreed.

- Backend storage
- Scheduled reminders

**Comment by SL-SWoods** [comment]
To list created, currently limited styling. 
![CheckList](https://user-images.githubusercontent.com/49903895/66221563-2713cc00-e6c7-11e9-9762-cebac64b7ade.png)

Has functionality to 
- Add new entries. This can be done via the '+' button or pressing enter on the input field. 
- All new entries are stamped with the current date & time. 
- Filter options to show 'All', 'Completed' 'Outstanding' tasks. 
- Option to delete all completed entries. 
- Can complete / revert any task, by selecting the icon to the left of the text entry. 
- Can delete the entry by selecting the icon to the right of the entry. 
- Uses the same scroll logic as other windows, so the scroll bar only appear when you are in the active window and the length allows it. 
- task list is stored within LocalStorage using `StockFluxHooks.useLocalStorage`

Current outstanding tasks 

- [ ] Push notifications when a new entry is added / completed / deleted
- [ ] Drag and drop re-ordering of elements

**Comment by SL-SWoods** [comment]
Work is being shelved as it is not required.
Current branch contains a work in progress for this. currently basic todo functionality is added, drag and drop functionality is not completed.

**Comment by AugusteBa** [comment]
Clsoed due to no longer needing this functionality.
