### ISSUE TITLE
Improve news app UI

### ISSUE THREAD

**Issue by jrhenderson1988** [ScottLogic/StockFlux#1268]
Bring the UI of the news app up to date with the rest of StockFlux. The launcher should be used as a base for UI.

**Comment by Johnston97** [comment]
![image](https://user-images.githubusercontent.com/23056937/65042837-9bbddb00-d951-11e9-9ff0-9a1766d44c7d.png)

**Comment by jrhenderson1988** [comment]
@markjose Currently, the news UI is up to date with the launcher as far as we can see. The screenshots on the StockFlux readme however, are out of date. Do you know what kind of UI changes you'd like to see for the news app. Luke has added a screenshot with its current state in a comment above.

**Comment by markjose** [comment]
The above looks good for now. Let's revisit later.
