### ISSUE TITLE
Integrate with Excel

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#285]

**Comment by owennw** [comment]
Do we want to do this, at some point in the future?

**Comment by bjedrzejewski** [comment]
We need to discuss what we would like to do with excel? Save data to Excel?

**Comment by owennw** [comment]
Yeah it's a case for after we've released v.1

**Comment by msuperina** [comment]
Related to https://github.com/ScottLogic/StockFlux/issues/968
