### ISSUE TITLE
Brief display of "no favourites" message when app opens

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#326]
If possible I'd like to delay the visual rendering until angular has finished intialising? Or something to that effect.

**Comment by WPFerg** [comment]
This is because although the favourites are added by Angular, it takes time to fetch the data from Quandl. The easiest way to wait is to count the responses from Quandl, until `responses === stocks`, then show

**Comment by WPFerg** [comment]
An easy-ish way to do this would be to replace "no stocks" with a loading message. I think the additional wait for Quandl to return before showing the window would make the app feel more unresponsive.

**Comment by ColinEberhardt** [comment]
I'm not sure whether to open a new issue for this - but when you tear out a tile, you also see the effect of the application 'bootstrapping'.

Perhaps you should make have a class that is part of the HTML template itself that hides the application, then remove this class once Angular has bootstrapped?

**Comment by WPFerg** [comment]
@ColinEberhardt Do you mean have a big, empty window whilst the application is bootstrapping? Also, in tear out cases, angular will have already bootstrapped, due to windows being pooled.

**Comment by ColinEberhardt** [comment]
I'm not sure what's best, a big empty window, or a loading indicator - either way it should be something that looks like it is 'by design', rather than the current behaviour which is just the way it worked 'out of the box' ;-)

**Comment by WPFerg** [comment]
There's a PR in for some loading text, which could work as an interim if we wanted to add a loading spinner.
