### ISSUE TITLE
shrink to mouse on clicking the compact view icon

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/StockFlux#350]

**Comment by akhmorgan** [comment]
It looks like the only way to do this is to have the expand icon in the compact view the same distance from the top-right corner of the window as the shrink icon in the regular view. This would go against the current design which calls for the icons to go: min, shrink, max/restore, close in the regular view, and just min, expand, close in the compact view

**Comment by owennw** [comment]
Is the idea here that after clicking the compact button the mouse should immediately be over the expand button?

**Comment by akhmorgan** [comment]
yes, that's the idea. At the minute, I'm not sure it's going to be possible without changing the layout of the icons in either the compact view or the full view.

**Comment by owennw** [comment]
It's *possible*. You can recruit http://cdn.openfin.co/jsdocs/stable/fin.desktop.module_Window.html#moveBy just after the click.. which might look weird.

**Comment by akhmorgan** [comment]
yeah, I considered that but like you say, it might look weird. Plus it seems like a bit of a desperate measure to me for a very small ux gain

**Comment by akhmorgan** [comment]
I'll give it a go though and see what it looks like
