### ISSUE TITLE
Don't tear in to hidden (background) windows

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#359]

**Comment by owennw** [comment]
Will implement #369 to make the window more obvious instead.

**Comment by ColinEberhardt** [comment]
@owennw can you provide a description for this issue? and include why it is labelled 'wontfix'

**Comment by owennw** [comment]
When tearing out a card the window manager iterates over the open windows to find which ones overlap with the torn out card. However, we can't see a way with the current API provided to discern whether a given window is focused, or visible on the desktop (for example the window could be obscured, or in the background). Given that we decided to bring the chosen window to the front what a card is dropped into it, to show the user which window has taken the card.
