### ISSUE TITLE
Allow tearing out the last (single) fav- this should close the remaining window perhaps?

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#410]

**Comment by owennw** [comment]
#311

**Comment by bjedrzejewski** [comment]
@owennw but... why? I though this is a rather natural thing to do. I do it all the time on chrome (merge a single tab window into multi tab window, by tearout).

**Comment by rmarcalo** [comment]
I think the long-term ideal solution is to allow tear out and then merge within a new window. If this is not yet possible, then disabling the tear-out makes more sense.

**Comment by ColinEberhardt** [comment]
Duplicate of https://github.com/ScottLogic/StockFlux/issues/726
