### ISSUE TITLE
Recovering windows is broken.

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#414]
When you close last window, restart the app, often more than one window (with a few empty ones) show up. This is a big problem, as it breaks one of the key features for the demo.

**Comment by owennw** [comment]
I gave it a play here and I'm not sure if this is the cache speed issues again? If I look at the local storage before closing the windows it seems to behave well for me. @akhmorgan @WPFerg can you give this a look over too?

**Comment by WPFerg** [comment]
@owennw I'm getting the same errors. If I have 2 windows open, and close both, both are restored on the next start up with a bonus empty window.

**Comment by owennw** [comment]
@WPFerg You may need to be on top of the bug-fix branch, sorry. That's where I tested it.

**Comment by WPFerg** [comment]
@owennw No change. In fact, I got 3 empty windows, and my last closed window.

**Comment by owennw** [comment]
I've just given this a thorough test on latest and I don't get any extra empty windows opening, ever.

If I have multiple windows open in various states and force close the app these states are remembered and restored on next start up.

If I close them one by one to exit the app more naturally I am seeing on restart that multiple windows open, though.

**Comment by owennw** [comment]
@bjedrzejewski assigned to you for retesting.

**Comment by bjedrzejewski** [comment]
@owennw do you think its fixed?

**Comment by owennw** [comment]
I've never had the empty windows open in the first place.

**Comment by bjedrzejewski** [comment]
@owennw same issues still exist. Just tested from dev.

**Comment by bjedrzejewski** [comment]
it mostly works
