### ISSUE TITLE
Navigator chart should always be shown

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#418]

**Comment by owennw** [comment]
I think this will be a case of increasing the min width of the window.

**Comment by WPFerg** [comment]
The navigator appears on widths >992px, perhaps that as the new minimum? Or a nice, round, 1000?

**Comment by jleft** [comment]
FYI, since BitFlux 1.1.0 - assuming you're still using Less - you should be able to achieve this be overriding the relevant variables:

```less
@phone-landscape-nav-display: @show;
@phone-portrait-nav-display: @show;
@tablet-landscape-nav-display: @show;
@tablet-portrait-nav-display: @show;
```

**Comment by owennw** [comment]
#213 will update the version of BitFlux, after which we can do this issue. @bjedrzejewski I'll assign this to you, when #213 is closed you can unassign this case again.
