### ISSUE TITLE
Selectively apply pixel snapping

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#419]
Some icons are a bit blurry

![image](https://cloud.githubusercontent.com/assets/1098110/13315596/858cfadc-dba3-11e5-8b65-2d7ffe12124a.png)

I think 'crisp edges' would resolve this.

**Comment by WPFerg** [comment]
I can't seem to get `crispEdges` working in this instance. The candlestick is a background image, and I can't see a way to edit `shape-rendering` there. The only way around this that I can see is extract `candlestick-series.svg` from Bitflux, add in `shape-rendering='crispEdges'` and then override the `background-image`, which is fairly convoluted

**Comment by ColinEberhardt** [comment]
I think we should also pixel align the logo

![image](https://cloud.githubusercontent.com/assets/1098110/13319177/c19f4912-dbb7-11e5-9321-a3c616cd72f8.png)

**Comment by WPFerg** [comment]
The closest to pixel alignment I've gotten involves making the logo slightly smaller, but produces a better result. 
![image](https://cloud.githubusercontent.com/assets/7962948/13319565/7dc7bfd2-dbba-11e5-9ede-d8ed2ddb1f62.png)

**Comment by ColinEberhardt** [comment]
Rather than SVGs, I think these would be better as PNGs that have been rendered to specific sizes, which we then render aligned to pixel boundaries. That way Rui can be in charge of getting the font rendering / aliasing to work nicely!

**Comment by owennw** [comment]
Closed by #495
