### ISSUE TITLE
Initial chart should show more data

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#421]
I think it looks better as follows:

![image](https://cloud.githubusercontent.com/assets/1098110/13315645/ddf3b54e-dba3-11e5-8937-aa90e3a20d1e.png)

Out of interest, can we get more data from Quandl? What are the limits?

**Comment by owennw** [comment]
I asked @jleft about this the other day actually. Is there any progress on that?

**Comment by owennw** [comment]
#213

**Comment by ColinEberhardt** [comment]
Thanks for the ref to #213 - pushed that issue into the milestone just as a starting point for discussion.

**Comment by owennw** [comment]
I've messaged the BitFlux team and they'll add this to their API for the next release.

**Comment by jleft** [comment]
Merged in BitFlux's `develop` branch (not released yet). https://github.com/ScottLogic/BitFlux/pull/659

API example:

```js
// Show half the data by default
 bitflux.app().proportionOfDataToDisplayByDefault(0.5);

// Show all of the data by default
 bitflux.app().proportionOfDataToDisplayByDefault(1);
```

**Comment by ColinEberhardt** [comment]
It looks like this has been merged to master, so should be in the v.9 release? When I select a stock, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1098110/13523168/a991f542-e1eb-11e5-82fa-6ebe1517b902.png)

i.e. not much data!

**Comment by WPFerg** [comment]
This was under UX guidance from Rui

**Comment by owennw** [comment]
#494
