### ISSUE TITLE
We should be excluding weekends on the x-axis

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#432]
We just plot EOD data, so should skip weekends,

**Comment by owennw** [comment]
I messaged the BitFlux team about this earlier too, @jleft said he was going to have a look into it.

**Comment by ColinEberhardt** [comment]
OK, we should make a plan that ensures BitFlux changes for their next release include the ones we need :-)

**Comment by ColinEberhardt** [comment]
Looks like it is almost complete - but requires more testing. Let's leave this for a future release.

One in the very near future ...

**Comment by jleft** [comment]
[BitFlux 1.5.0](https://github.com/ScottLogic/BitFlux/releases/tag/1.5.0) has been released, which includes the weekends skipped on the x-axis.
