### ISSUE TITLE
Long stock titles overflow favourite cards

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#457]
![image](https://cloud.githubusercontent.com/assets/7962948/13358399/ffd66126-dca6-11e5-9ab7-ad2ab43af989.png)

Probably fixed with `overflow: hidden;` and `text-overflow: ellipsis`

EDIT: now it's fine, even though no changes have been made. Might just be a chance occurrence

![image](https://cloud.githubusercontent.com/assets/7962948/13358559/ce193680-dca7-11e5-9016-48d819d75b75.png)

**Comment by owennw** [comment]
Try adding IBM and then swapping the cards around.

**Comment by WPFerg** [comment]
Ah, that reproduces it. Looks like it could be the scrollbar

**Comment by owennw** [comment]
Should this go in the release?

**Comment by owennw** [comment]
Closed by #472
