### ISSUE TITLE
Clicking Scott Logic logo could open the SL website in the browser

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#482]

**Comment by WPFerg** [comment]
I don't think you'll be able to do this, since the toolbar has `-webkit-app-region: drag`, which captures all click/mouse events and doesn't pass it through to the page itself.

**Comment by owennw** [comment]
We could specify `webkit-app-region: no-drag;` over the picture, don't know if we want that too. (More of a UX than technical issue).

Also, we could extend the draggable toolbar over the toolbar icons and apply that styling to the icons themselves.
