### ISSUE TITLE
Sometimes tearout windows appear white, briefly

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#483]
Could be fixed by changing the bg colour?

**Comment by owennw** [comment]
My current best idea is to set the background colour of the tearout windows with the dark blue of the favourite card background, so make it less obvious.

**Comment by bjedrzejewski** [comment]
@owennw this is THE perfect solution.

**Comment by WPFerg** [comment]
Trying to set `<html style="background-color:black;min-height:100%">` on `tearout.html` still causes white background, albeit briefly. That should cause a black background instead, but doesn't have an effect. If I load that page in the browser and repeatedly refresh, it stays constant black, so I'm not 100% sure it's something we can fix.

**Comment by WPFerg** [comment]
Having a bit more of an investigate and attempting a refactor (by not appending/removing elements between windows and duplicating the element the once), I don't think it's something we can do.

**Comment by msuperina** [comment]
Cannot reproduce.
Will reopen if it happens again.
