### ISSUE TITLE
UX Issues [Chart]

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#494]
*Chart*:
- [x] Purple on RSI doesn't match visual style (Purple colour should be #9D97E5)
- [x] Current price line and label should have the same blue teal colour as depicted in the designs (they have a different blue colour in the newest version.
- [x] Line weight in the summary chart is too think, perhaps 1px less?
- [x] Indicator “close” buttons are rounded, but should be squared, with a 1 px teal border.
- [x] The default timespan for the chart is too broad, making the chart too compressed. I suggest a default of 31 days.

*Summary Chart*
- [x] should be aligned with the separator line for the Closed Windows icon,
- [x] extending the main chart a bit further down
- [x] reducing spacing between the two charts to around 20px below the date labels

**Comment by owennw** [comment]
Closed by #498
