### ISSUE TITLE
UX Issues [Windows Menu]

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#497]
**Closed Windows Menu**
- [X] Increase text size of date to 12px,
- [X] Increase text size of stock symbols to 14px,
- [X] Add arrow pointing down towards icon.
- [X] Add a separator line above the icon (similar to the ones in-between cards), but reduce its top and bottom margins
- [x] Padding-bottom is not the same as top. Should have around 15 px for both.
- [ ] When opening a previously closed window, the top-right corner buttons did not appear, and the overall application was frozen. (*edit: I can't reproduce this*)

**Comment by owennw** [comment]
Is point 5 still outstanding?

**Comment by WPFerg** [comment]
Nope

**Comment by owennw** [comment]
I'd suggest splitting point 6 into a different issue, not with the milestone, and closing this one.
