### ISSUE TITLE
When you have no windows to re-open the presence of the icon is confusing

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#510]
On a fresh install the icon that is used to open previously closed windows appears active. It highlights on mouse over etc ... But when you click it, nothing happens.

From a user perspective it feels like something is broken.

**Comment by owennw** [comment]
We've felt this too. Perhaps the icon should only show if there are closed windows? The hover state is governed by CSS so it would be a considerable refactor to change it to disable the icon (see #406 too).

**Comment by bjedrzejewski** [comment]
I will just make the icon not show

**Comment by owennw** [comment]
I guess that will involved toggling the whole bottom section, and then having it appear when you closed a window?

**Comment by ColinEberhardt** [comment]
> I will just make the icon not show

:+1:

**Comment by bjedrzejewski** [comment]
I am trying to make it work, but it seems harder than it looks, so if anyone has a quick fix/idea, please chip in :)

**Comment by WPFerg** [comment]
`opacity: 0.5` to make it look 'disabled', so when it's inactive it's still apparent that's where the button is?

**Comment by bjedrzejewski** [comment]
The problem is updating it reliably when other windows close. Now it just checks when you click on it.

**Comment by WPFerg** [comment]
Closed by #547
