### ISSUE TITLE
Add a splash screen / loading indicator

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#511]
Can we have a splash screen or loading screen?

**Comment by owennw** [comment]
The brunt of the opening time, I think, is on the OpenFin side for initiation. Any splash screen would also be in the OF app and so would take just as long to load (I think).

**Comment by owennw** [comment]
We've investigated adding a splash/intro screen to the app as it starts up, before the main windows are ready. However, that screen still must load after OpenFin has initialised.

Overall approximately 75% of the time seems to be OF initialisation, leaving about 25% of the time with a visible intro screen (which is yet to be designed).

I'm not entirely sure if we want a splash screen, and if we do whether it's worth it.

Besides that, I don't think we can find a way to speed up the opening.

**Comment by mic-smith** [comment]
Did we try this with the `splashScreenImage` option in app.json or as a custom splash?
splashScreenImage version shows pretty quickly for me.

**Comment by WPFerg** [comment]
I think it was a custom splash

**Comment by ColinEberhardt** [comment]
Nice idea @mic-smith - definitely worth a try.

**Comment by mic-smith** [comment]
@rmarcalo Could we please have a png for the splash screen?

**Comment by rmarcalo** [comment]
Sure. I will make a screen with the application skeleton and a loading/welcoming message.

**Comment by rmarcalo** [comment]
I wanted to make a splash screen which was basically an empty version of the app (with the two tabs on the left, no buttons and a "Loading StockFlux ..." message written. 

However, for this to serve its UX purpose, the size of the two tabs would need to coincide exactly with the real tabs as they are loaded. Since I will be putting things into a single PNG, I imagine there will be distortion based on the window size, is this the case? Should I forget this solution because of that limitation, or are there ways to ensure the horizontal proportion will be kept?

**Comment by mic-smith** [comment]
I think it would be tricky to get an app skeleton splash screen to the real app transition to look smooth.
The splash screen image is shown at it's native resolution and centred on primary monitor. It's not shown in the main apps window and the main app isn't centred when it loads. 

Is it worth having a none app skeleton version so we don't need to keep the image in sync with app changes? Maybe a variation on the larger favicon would work?

**Comment by rmarcalo** [comment]
I will look into making a more sophisticated splash screen then, although this may take considerable design effort, so it will be something for a future release.

**Comment by rmarcalo** [comment]
This issue will take a bit more time, as it has been expanded to include a logo redesign for StockFlux (instead of D3FC).

**Comment by rmarcalo** [comment]
After a few design iterations, I wanted to share with you the splash screen for the app, which includes the new StockFlux logo. I'll create a separate story for the new icons. The transparent PNG is supposed to be placed over a background with colour #1A212A (as the example shows).

![selected designs](https://cloud.githubusercontent.com/assets/13066377/14139723/97c2c3b0-f66c-11e5-8160-80d25c78e8a8.png)

![splash logo](https://cloud.githubusercontent.com/assets/13066377/14139730/a287ac2a-f66c-11e5-9b71-66e439c37042.png)

**Comment by mic-smith** [comment]
@rmarcalo Nice :) For the splash screen it just displays the png as is, so I've saved it with the specified background.
