### ISSUE TITLE
After clearing the cache an re-opening no stocks are shown

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#512]
This may not be a bug, as this isn't something I'd expect a user to do, but it feels a bit fishy.

Steps:

1. Close app
2. Delete OpenFin cache
3. Open app, no sticks are shown in favourites
4. Open search and add a single stock
5. The stock selected in (4) is added to favourites, but all of a sudden the default stocks (AAPLS, MSFT, TITN ...) also appear

**Comment by WPFerg** [comment]
@ColinEberhardt I can't reproduce this, after deleting the cache and reopening it, I get stocks appearing

**Comment by ColinEberhardt** [comment]
I'll retry with v9.1

**Comment by WPFerg** [comment]
@ColinEberhardt Any update on this? I'm happy to close it now since I think we'd have noticed it had it still been apparent.

**Comment by ColinEberhardt** [comment]
re-tested and it works just fine now - thank @WPFerg
