### ISSUE TITLE
Moving tiles between windows sometimes fails.

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#515]
I have two windows open in compact view.

I tear out a tile from one, and add to the other. It is removed from the first, but does not re-appear in the second window.

**Comment by WPFerg** [comment]
I got this, and trying to move empty that window results in:
![image](https://cloud.githubusercontent.com/assets/7962948/13525973/be563b30-e1fc-11e5-8dc0-953da2f718f9.png)
Possibly an angular watcher not working/updating as it should
