### ISSUE TITLE
When toggling compact view there is quite a bit of UI 'jank'

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#516]
Needs smoothing ....

**Comment by owennw** [comment]
#387, #326

**Comment by WPFerg** [comment]
I believe a decent fix for this would be removing the `ng-if` on the Showcase-Controller.

**Comment by akhmorgan** [comment]
I think it's going to be a little more complicated than that. My first thought is to add a flag to say when the window is transitioning between compact and full, then disable all css animations and transitions whilst that flag is present.

**Comment by WPFerg** [comment]
Closed by #571
