### ISSUE TITLE
There is no visual indicator that shows when a tile will 'drag in' to a window

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#524]
When I have quite a few windows open, I often find myself trying to tear out a tile, but finding that it docks with an existing window. There are a couple of issue here:

1. There is no visual cue associated with 'drag in'
2. The drag-in occurs over the entire window, I think drag in / drag out re-order should always be 'scoped' to the favourites pane.

**Comment by owennw** [comment]
This might be a biggy :)

**Comment by owennw** [comment]
Closed in favour of #357
