### ISSUE TITLE
Drag icon is a bit hard to see, not obvious what it will do

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#533]

**Comment by rmarcalo** [comment]
The contrast of the drag icon is something that concerns me too, although on my screen I see it well. If you find that in your screens it isn't visible, then I'll make it lighter. In regards to its meaning, a drag handle is the most commonly associated symbol we can have with "move", and I hope that the cursor change helps convey this message. If the usability is proven unclear, I would reinforce what is does by having the card jump a bit when clicking this icon, showing that the card is detached.

**Comment by owennw** [comment]
The cursor does help I think, but yes the contrast can be tricky. Given one of the main showcases of this application is the tearing out I think this icon should be as visible as possible. We can't guarantee the monitor/settings of any user too.

**Comment by rmarcalo** [comment]
It wasn't doing the jump but upon reloading the app I realise it already behaves like I was mentioning. I think increasing the contrast might help it (I will make it the same colour of the favourites tab icon).

**Comment by rmarcalo** [comment]
I've added a lighter drag-handle to the google drive, which will hopefully be more visible.
