### ISSUE TITLE
Last closed windows icon is a bit unknown

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#536]
The button wasn't obvious in its use, and the card didn't help with that.

**Comment by owennw** [comment]
Maybe #513 is sufficient to close this.

**Comment by owennw** [comment]
Also #510 should help with it too.

**Comment by WPFerg** [comment]
Together it's probably enough to close this, IMO

**Comment by bjedrzejewski** [comment]
Referenced issues closed
