### ISSUE TITLE
Alt-Tab whilst tearing out breaks the tearout window

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#538]
You can mouse up and move the mouse around without the card following/expanding/etc

Same with the start button

**Comment by WPFerg** [comment]
Could this be fixed by adding a `blur` event listener to do what `mouseup` does?

**Comment by owennw** [comment]
I've been looking at where events are captured, and it's not at all obvious where. I'll give that a go, this issue isn't a priority though.
