### ISSUE TITLE
When moving from compact to 'full' view you can move the draggable region off screen

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#556]
To reproduce:
 - Select compact view
 - Move to the far left of the screen
 - Toggle back to full view

That window is now stuck!

Maybe we need to be more 'generous' with what is and is not draggable? Perhaps make the 'dead' areas around the title bar icons draggable?

**Comment by owennw** [comment]
I think making the areas around the icons draggable is both useful and easy, so would opt for that.

**Comment by WPFerg** [comment]
I agree. Perhaps make the whole of that area draggable, and have `-webkit-app-region: nodrag` on the icons themselves?

**Comment by owennw** [comment]
Yes that's the solution I was thinking of.

**Comment by owennw** [comment]
Making the area around the icons (but not the icons themselves) draggable isn't so hard. There's a branch for that at the moment.

The issue now is that because the icons are surrounded by a `-webkit-app-region` we lose mouse events when leaving the icons. This means that until the mouse leaves the toolbar any hovered icon stays active.

**Comment by owennw** [comment]
See the `toolbar-drag` branch.

**Comment by ColinEberhardt** [comment]
While you're fixing this, there's one other super-minor issue! The minimize icon has a hit-area that is much smaller than the other three title-bar icons. I think all of them should have the same, square, hit area

**Comment by owennw** [comment]
Yes I've felt that too, it's just the images themselves that are clickable at the moment. Feels like a separate issue to me.

**Comment by ColinEberhardt** [comment]
I'd be happy for you to raise an issue on this subject :-P
