### ISSUE TITLE
When tearing out there is a quite a bit of window movement 'jank'

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#560]
When I tear out a tile I can see the window reposition itself a few times. Would be good to get this buttery smooth!

**Comment by WPFerg** [comment]
Is this on the tearout card itself? If so, #528

**Comment by ColinEberhardt** [comment]
No, this is when the new window is constructed - the new window is briefly visible in a different location before moving to the correct position.

**Comment by owennw** [comment]
Is that when lifting the card out of the application, or dropping it outside to create a new window (or both)?

**Comment by ColinEberhardt** [comment]
erm ... I'm on my Mac right now, so cannot re-test. I observed this behaviour quite frequently, just try tearing out a few times to create new windows in various locations and watch out for the window position jitter

**Comment by owennw** [comment]
I believe that @WPFerg and myself haven't been able to reproduce this.. could be tied to machine performance?

**Comment by bjedrzejewski** [comment]
Just for the record- to get that reproduced you need to resize your window first and then do the tearing out.
