### ISSUE TITLE
Restore a window with no favourites

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#573]
Should you be able to restore a closed window if it has no favourites?

**Comment by bjedrzejewski** [comment]
@WPFerg another idea- if there are no recently closed, keep the icon there and change the content for: 'open a new empty window'

**Comment by rmarcalo** [comment]
I would prefer to discourage the user from having empty windows, as have this be a rare state that only happens if you unfavourite everything. Therefore, I would opt for empty windows not to be shown on the Close Windows menu at all.

**Comment by owennw** [comment]
#726
