### ISSUE TITLE
Need a more prominent link to GitHub

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#575]

**Comment by owennw** [comment]
It was brought up in the meeting with @ColinEberhardt that the link to GitHub should be more noticeable, given that this is a demo.

**Comment by rmarcalo** [comment]
I think having the text: Github Version: xxxx , in the same position as the current version number, would be enough to make the user access it (specially the knowledgeable user more likely to want to access github.

**Comment by ColinEberhardt** [comment]
@rmarcalo couldn't we squeeze in a little octocat?

![image](https://cloud.githubusercontent.com/assets/1098110/13667986/754aa426-e6b1-11e5-87d9-7651ae28e0eb.png)

(perhaps a bit smaller than that one!)

It is a widely recognized logo, so more noticeable than a line of text.

**Comment by rmarcalo** [comment]
I would be worried about it becoming too prominent. Will all users of this know what github is? This really depends on the target audience, I was trying to avoid having users click on it thinking it's part of the app and being led into github which breaks the experience. Having an icon makes this a button equal to all others in the application.

**Comment by ColinEberhardt** [comment]
That's a good point. I'm happy to go with the updates as per #583
