### ISSUE TITLE
When windows get restored, they are not set to their previous size.

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#579]
How to reproduce:

1. Open the app
2. Change sizes of a few windows
3. Close the app (from gitbash)
4. Open the app
5. See the windows in default size

**Comment by owennw** [comment]
Curious, usually restoring the size of the window is handled for us, assuming the appropriate name was given to the window and the cache has caught up. Just tried it and the windows seemed to be in the correct positions, with the correct stocks.. so the name must be correct. 

Did we start resizing new windows on startup ourselves perhaps?

**Comment by bjedrzejewski** [comment]
I think this is what might be happening. I am looking into the tear-out issue now and it is not that easy.

**Comment by bjedrzejewski** [comment]
On restart- they blink in the correct sizes before being changed to default.
