### ISSUE TITLE
Hit target for minimise icon is small

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#587]
Most applications don't have just the image clickable, but a square area around it, so that all the (toolbar) icons have the same size hit targets. I feel we should be doing the same.

**Comment by akhmorgan** [comment]
This should probably be fixed across all icons.

**Comment by WPFerg** [comment]
Would this be a case of making all the icons the same size?

**Comment by akhmorgan** [comment]
This is probably due to the click being bound to the image itself, where it should probably bound to a container around the icon that is a standard size.

**Comment by rmarcalo** [comment]
Would it be preferable to have this particular image the same height as the others with empty space?

**Comment by bjedrzejewski** [comment]
@rmarcalo I think this is something we should handle on the software side. Just tell us how many pixels around the image should be clickable and we should make it possible, rather than you making custom assets for that.

**Comment by rmarcalo** [comment]
The other icons are all 14x14px, therefore I would suggest a centered hitbox of 16x16px.

**Comment by chriswilty** [comment]
👍 This also feels like an easy win.

**Comment by AndySmithSL** [comment]
Investigated this issue and it appears to have been fixed. The minimise icon is only 4px high but it is surrounded by a 'hit' box that is currently 30x16px which is more than enough.

However this issue has highlighted another problem with the styling and icons in the Stockflux app. Some of the icons and spacing between them do not comply with the UX specifications for Stockflux and additionally the styling is also tightly coupled meaning changes can't be made without consequences across the entire app. The styling across the entire app needs to looked at and tidied up.

This issue will be closed and a new issue raised to deal with the styling issues.

**Comment by AndySmithSL** [comment]
Closing issue, see issue #1005 for details concerning cleaning up the styling.
