### ISSUE TITLE
Create a strategy for backwards compatibility with releases

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#592]
When we do the initial release we can expect a number of users to install the app. Ideally we should have a strategy in place that prepares us for future upgrades of app state.

Perhaps we should store the version number as part of the app state?

**Comment by ColinEberhardt** [comment]
From release we should probably use semantic versioning based on the effect a change has on the app state? This would give us a firm basis for deciding the correct number.

**Comment by WPFerg** [comment]
Most of the window stock/indicator state information is stored in Local Storage. It might be useful to store the version the app last ran there, too.
If we're moving to semantic versioning, then perhaps on a major (breaking) update, reset the stored state to the default one?
