### ISSUE TITLE
Investigate migrating to React / Redux 

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#593]
Why you say? Have you gone mad????

I'm not proposing this just because React / Redux are the new 'hotness'. They have some genuinely useful features that enable concepts like hot-reload and time-travel:

https://www.youtube.com/watch?v=xsSnOQynTHs

Bringing these concepts to desktop development would be amazing. Although it does require quite a bit of chance. Clearly we will need React and Redux, but also Webpack.

If we're going to do this, my preference is sooner rather than later.

**Comment by ColinEberhardt** [comment]
This should include #467

**Comment by msuperina** [comment]
@ColinEberhardt It looks to me both this one and #467 can be closed ?
