### ISSUE TITLE
Clarify the usage of Quandl API

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#594]
What are the rate limits? And how do they effect us? I know we have discussed this a little in the past, but I don't feel 100% comfortable that we are covered.

Can we use this issue to clarify the situation then update the README (either for developers or end-users) accordingly.

**Comment by WPFerg** [comment]
The rate limits, from the [API Page](https://www.quandl.com/docs/api?json#rate-limits):

> Authenticated users have a limit of 2,000 calls per 10 minutes, and a limit of 50,000 calls per day.

So, I don't think they'll effect us unless the app blows up in popularity.

**Comment by ColinEberhardt** [comment]
Thanks @WPFerg - I do wonder whether we should use a different key for development? That is going to be the main contributor towards that daily limit.

**Comment by ColinEberhardt** [comment]
I've moved to the next milestone ...

**Comment by owennw** [comment]
Closed by #662
