### ISSUE TITLE
Create a test 'environment'

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#595]
Currently all of our releases are immediately public (hooray for continuous delivery!). We need a mechanism that allows us to distribute multiple versions of the application so that we can do some testing on a release before pushing it public.

**Comment by bjedrzejewski** [comment]
@ColinEberhardt can't we use the release candidate mechanism? This automatically appears on gh-pages and is ready for testing.

**Comment by bjedrzejewski** [comment]
You can have for example:

https://github.com/ScottLogic/StockFlux/blob/gh-pages/10.0.0-rc.2/StockFlux-10.0.0-rc.2.zip

Pointing to the `10.0.0-rc.2`

**Comment by mic-smith** [comment]
Release candidate and dev versions available through gh-pages for testing before merging to master.
