### ISSUE TITLE
Ensure all icons are crisp

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#599]
Some are still blurry!

**Comment by bjedrzejewski** [comment]
@rmarcalo the one icon I know does not have the right size is the recently closed windows. It should be 21px by 21px but is 30x30 currently.

If you don't like the crispiness of the other icons- this is the MacBook Retina screen that you are using. We can add retina icons as well (x2 scaling), not sure though if we want it in the first release (this is a bit more work).

**Comment by ColinEberhardt** [comment]
>  this is the MacBook Retina screen that you are using

OpenFin doesn't work on Mac yet, so we'll hold off on retina images for now ;-)

**Comment by bjedrzejewski** [comment]
I guess it's just his one icon then.

**Comment by rmarcalo** [comment]
I am perhaps too used to the crispness of the Retina screen and I'm testing everything through a virtual machine. Currently the icon that bothers me the most is the "compact view". It's also one the more complex ones, but I'll have a quick review of best practices regarding PNG icons, to make sure I'm doing the best I can. I'll fix the "Closed Windows" icon in the meantime.

**Comment by bjedrzejewski** [comment]
Thanks, you can put the new icon here, so that someone can then easily fix.

**Comment by rmarcalo** [comment]
I've attached them below and added them to the google drive folder:
![closed_tabs_new](https://cloud.githubusercontent.com/assets/13066377/13706175/dce88090-e79b-11e5-9aa4-26045d19552b.png)
![closed_tabs](https://cloud.githubusercontent.com/assets/13066377/13706176/dd0a6458-e79b-11e5-8163-921b087b8453.png)

**Comment by bjedrzejewski** [comment]
Closed until we decide to support retina.
