### ISSUE TITLE
When no favorites in the window, bitflux area looks a bit empty

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#603]
Marcio suggested that we could put something there, maybe a screenshot showing how to add favorites, or some friendly message?

Open for discussion.

**Comment by WPFerg** [comment]
I quite like the idea of a screenshot showing how to do stuff. Good use of the dead space

**Comment by akhmorgan** [comment]
Yeah a little instructional infographic would be nice.

**Comment by rmarcalo** [comment]
I am currently working on this.

**Comment by rmarcalo** [comment]
I've been working on this design for the empty chart area. Could you give me some feedback on the wording of each step, in terms of how well explained they are / simple to read ?

![no favourites](https://cloud.githubusercontent.com/assets/13066377/13927829/3b1596ca-ef8b-11e5-939f-0e431f1542be.png)

**Comment by WPFerg** [comment]
I really like it @rmarcalo :+1:

**Comment by owennw** [comment]
I too very much like it. One thing though is step (3) might imply that these stocks can't also be selected from the Search tab?

**Comment by rmarcalo** [comment]
I think it does imply that it is intended that way, but I think that isn't harmful, since the selection from Search isn't the ideal way of interacting with the app (I see it more as a preview than a full selection).

**Comment by mbssantos** [comment]
@rmarcalo Is there an SVG version I can use?

**Comment by rmarcalo** [comment]
Sure! Would would like it with or without the background colour?

**Comment by mbssantos** [comment]
without is probably better :+1:

**Comment by rmarcalo** [comment]
Just noticed that the way this was made would require quite a bit of rework to be exportable as SVG, could you give me an idea of why you'd want it as SVG instead of PNG? I can export it 2x if it's looking pixelated.

**Comment by mbssantos** [comment]
png works fine, was just so we could easily support all sizes.
The min window size is 918x510 making the minimum image area 618x460.

What should it look like for min and maximized?

**Comment by rmarcalo** [comment]
![nofavourites](https://cloud.githubusercontent.com/assets/13066377/14979411/0f9dab9e-111a-11e6-9ae9-1da676ac40af.png)

Sorry for the delay! The PNG should scale down well, but the maximum size should be 1060x500.

**Comment by mic-smith** [comment]
Thanks @rmarcalo. The attached image seems to have a slightly different background colour than the app. We currently have #1A212A for background, where as the image background is using #1A1F25.
Would it be possible to get it updated?

**Comment by rmarcalo** [comment]
No problem! I've now attached the updated version.

![nofavourites](https://cloud.githubusercontent.com/assets/13066377/14980676/f3cf6224-1121-11e6-9363-86b6064528e8.png)

**Comment by mic-smith** [comment]
Thanks :)

**Comment by ColinEberhardt** [comment]
Just re-opening this issue - through testing I've spotted a minor issue ...

When you start up StockFlux you can briefly see this image flash before you before the chart data is loaded. This looks a bit ugly and disconcerting!
