### ISSUE TITLE
Ability to compare two stocks on the same chart

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#604]
Patrick suggested that this could be a useful functionality.

**Comment by bjedrzejewski** [comment]
Potentially plot multiple chart within one window.

**Comment by rmarcalo** [comment]
This would potentially require a massive design change, as I am not sure how to integrate this with the tabbed system for selecting cards. It's certainly possible, but could become a big effort as it fundamentally changes the user flow.

**Comment by ColinEberhardt** [comment]
I think this is just too big a change ... closing for now.
