### ISSUE TITLE
Recently closed window icon and position is confusing for new users

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#607]
There is some empty space on the bottom with the icon that has no obvious functionality. The meaning of the icon is not clear.

**Comment by rmarcalo** [comment]
I will conduct a few testings within the UX team tomorrow and this will be a focus.

**Comment by rmarcalo** [comment]
From my user testings there were no difficulties recovering windows, without any suggestion or advice from me. People experimented with the application (as expected) and quickly understood what this button did. The icon might not tell them directly what it does, but none will, as long as you click on it and it starts making sense I think the interaction works. 

I am considering moving the Compact mode button to this same place, as I believe it might be fitting in terms of mental model and better balance the visuals.

**Comment by owennw** [comment]
Might be a decent idea to move it, it would certainly preserve user experience. I agree that the icon is fine -- if you don't know what it does then give it a go, after all it only appears after a window is closed (so in some sense is reliant on someone tearing out and closing a window first). It also does come with a tooltip!
