### ISSUE TITLE
Use something like a 'snackbar' for notification/undo functionality?

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#608]
Marcio suggested that we could make use of:

http://www.material-ui.com/#/components/snackbar

for notifications. For example when you close a window, you could undo that action quickly? Or when you removed favorite you could bring it back?

It is a bit long winded explanation, but 'undo' functionality could make it more modern/usable.

**Comment by WPFerg** [comment]
Notifications was one of the things on the roadmap for the future, this could be a good starting point for trying them out.

**Comment by jdhodges** [comment]
Closing due to openfin notifications issue #967
