### ISSUE TITLE
Scrollbar not visible over a selected stock

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#615]
If you have a long list of favourites, and mouse over/select a stock such that the scrollbar is entirely within that favourite card's bounds, it "disappears"

![Example of Issue](https://cloud.githubusercontent.com/assets/7962948/13743182/29ae773e-e9d8-11e5-8f0c-15439fb0e3c2.png)

**Comment by rmarcalo** [comment]
Maybe having the scrollbar lighter than the rest, rather than dark will solve this and the problem of its overall visibility - just won't look as slick. I suggest using the background colour of the search tab, with a 80% opacity applied.
