### ISSUE TITLE
Closed Windows should keep a permanent log

### ISSUE THREAD

**Issue by rmarcalo** [ScottLogic/StockFlux#627]
I find the Closed Windows functionality to be only truly useful if it remembers windows from past sessions even after I close the application. My build does not currently do this, and I wonder if it's a technical limitation, but I think this would be a major usability improvement to include.

**Comment by WPFerg** [comment]
It's a result of the upgrade code (designed to be run when versions change/other things mismatch) running at each start up because of it being a release candidate. It's already been fixed, and I'll probably update the latest release tomorrow with that and a few other fixes/improvements. :)
