### ISSUE TITLE
Line separator before stock cards

### ISSUE THREAD

**Issue by rmarcalo** [ScottLogic/StockFlux#631]
While I intentionally left this out of the design for initial aesthetic reasons, I think the favourite tab would be more balanced if a line separator (similar to the one before the Close Windows icon) was introduced below the Favourites Tab icon, thus separating this icon from the first stock card. The same line would be on the Search tab, right below the text input.

![visual spec - latest](https://cloud.githubusercontent.com/assets/13066377/13772614/05b7f5a2-ea8d-11e5-8b53-cd41d3be0f4a.png)

**Comment by mic-smith** [comment]
Should the line be the same colour on both tabs and should they show on the collapsed versions?
This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/17762186/13776189/bc247fc8-eaa0-11e5-91cf-7104553cb9e1.png)

![image](https://cloud.githubusercontent.com/assets/17762186/13776223/f2263512-eaa0-11e5-9a62-ee7afb3105fc.png)

![image](https://cloud.githubusercontent.com/assets/17762186/13776229/f766023c-eaa0-11e5-9fd1-3caf3a4bf34a.png)

**Comment by owennw** [comment]
@rmarcalo

**Comment by rmarcalo** [comment]
The search tab line could have the colour of the favourite tab background instead, to make it less striking.
