### ISSUE TITLE
Minichart looks weird if there's not enough history to render

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#632]
Only seems to appear on certain stocks, for example:

![image](https://cloud.githubusercontent.com/assets/7962948/13773377/cfc02a24-ea90-11e5-897a-3a687cdb36a8.png)

**Comment by rmarcalo** [comment]
Is this due to an error or just lack of data? A message could be displayed instead of the chart.
Is the current price updated, or from a point in the past which got frozen? The chart could be made to adapt to situations were data isn't continuous, depending on what may happen.

**Comment by WPFerg** [comment]
I think it's the lack of data (judging by what bitflux is rendering):
![image](https://cloud.githubusercontent.com/assets/7962948/13774626/d67322f2-ea97-11e5-814b-483e90525b5b.png)
