### ISSUE TITLE
Expanding from compact will never revert to a maximised window

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/StockFlux#633]
This is similar to #619 

If you have a maximised window and you click the compact icon, and then click the expand icon, you'd expect the window to revert to it's previous state of maximised, but it does not.

This is because the `maximised` flag in the toolbar controller is set based on the `maximise `and `restore` events on the window. Which makes sense, however the `restore `event, which sets the flag to false is triggered by the window becoming compact, and so the state is not maintained correctly.

**Comment by WPFerg** [comment]
How would we like this to act? Ideally we'd want it to restore to maximised from both compact and recreating closed windows. Would it be best to check widths/heights of the monitor the window is on, and if it's equal (and the window is wholly on that monitor), maximise?

Or just have it so there's a flag to say it's maximised and use that (although the question would then be whether it's worth persisting this in LocalStorage too)?

**Comment by owennw** [comment]
I don't like checking window sizes against monitor size at all. There's a maximised flag, let's use it! It could be worth persisting, that's more a UX idea than a technical one.

**Comment by WPFerg** [comment]
Thinking about it, even persisting the flag would do the job, so using monitor information wouldn't be needed
