### ISSUE TITLE
Loading search results messages remains after clearing a none matching search

### ISSUE THREAD

**Issue by mic-smith** [ScottLogic/StockFlux#639]
Do a new search that doesn't match e.g. \# and then delete the search term.
Results section shows a "Loading search results..." message rather than being cleared.

**Comment by jackarnstein** [comment]
[bandicam 2016-03-15 16-41-55-696.avi](https://files.zenhub.io/56e83b95a0b9fd8b565953d0)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

came across this issue myself, thought id add the video i made for it incase anyone wanted one
