### ISSUE TITLE
How to "crash" the application in just a few clicks...

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/StockFlux#650]
Im not too sure what the exact cause is. But I will work further on trying to identify it tommorrow. It seems like the application will close if you open a recently closed tab, close it, reopen it and close it again (quickly).

[bandicam 2016-03-15 17-08-05-321.avi](https://files.zenhub.io/56e841d1a0b9fd8b565954ab)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by owennw** [comment]
I know that OpenFin hates having two windows with the same name open, could be the source of a crash. Wouldn't get hung up on that though.

**Comment by WPFerg** [comment]
I agree @owennw; I think it'll just be a case of removing the item from the closed window list as soon as the request to open the window has gone through (as opposed to when the window is displayed then the 'closed' flag is set to `0`)
