### ISSUE TITLE
The app doesn't reliably update its state

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#665]
If I start the application (from its icon), add some favourites, close the app, then re-launch, I don't reliably see the new additions in the list of favourites.

**Comment by WPFerg** [comment]
I believe this is an issue with Openfin, I've run a test project using the code
```
    var setNumberText = function(version) {
        var ofVersion = document.querySelector('#of-version');
        ofVersion.innerText = version;
    };
    document.addEventListener('DOMContentLoaded', function() {
        //OpenFin is ready
        fin.desktop.main(function() {
            var version = (Number(localStorage.getItem('num')) || 0) + 1;
            localStorage.setItem('num', version);
            setNumberText(version);
        });
    });
```
And the number doesn't increment between restarts if you close the window fast enough, otherwise it does. Potentially some async stuff going on, but for now I'll add the wontfix.
