### ISSUE TITLE
Use directory structure for releasing to gh-pages

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#676]
The idea is to use directory structure for gh-pages release.

There most likely will be:
-Latest release
-Development
-Old releases

Details will become more clear once the pr is in

**Comment by owennw** [comment]
Should this be in the first milestone?

**Comment by bjedrzejewski** [comment]
I don't think so. To do this well may take some time and I wouldn't want to hold up much anticipated release because of that.

**Comment by bjedrzejewski** [comment]
Although if it is done well in time I think we should put it in.

**Comment by owennw** [comment]
@bjedrzejewski Can this be closed now?

**Comment by bjedrzejewski** [comment]
yes, thank you
