### ISSUE TITLE
Create a landing page for the application on github pages

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#677]
Similar to [BitFlux](http://scottlogic.github.io/BitFlux/) perhaps. Maybe in React?!

Linking to #676

**Comment by ColinEberhardt** [comment]
How would you reach this landing page? Can you explain the usage?

**Comment by owennw** [comment]
The usage would be for easier access to the different versions of the application -- they could be displayed there in a graphical format instead of relying on tweaking the zip URL from the README. The page would be on http://scottlogic.github.io/StockFlux/

**Comment by msuperina** [comment]
@ColinEberhardt @owennw is this question still relevant ?
