### ISSUE TITLE
Visual and Interaction Adjustments

### ISSUE THREAD

**Issue by rmarcalo** [ScottLogic/StockFlux#685]
Hi,

Following more of the feedback I got from the beginning of the week, I would like to propose a few changes to the visuals and interactions of the application. They can be seen in the document below:

![sidebar revisions](https://cloud.githubusercontent.com/assets/13066377/13881437/d0ebe548-ed18-11e5-8893-9944184d9134.png)

To these changes I would add that I changed the Scott Logic logo to align with the chart & Stock title, rather than the previous location of the chart/indicator buttons.

Let me know if you have any questions. I think the new position of the compact view icon in particular should be further discussed.

Rui

**Comment by owennw** [comment]
@rmarcalo That last idea in the favourites tab looks awesome! The favourites and search expanding and collapsing should be quite easy, as should any colour changes and repositioning of icons etc.

The only thing that might be more difficult is rearranging the compact view (and perhaps the favourite card height.. though I'd hope that's simple enough).

All looks very good though!

**Comment by owennw** [comment]
@rmarcalo The colour change mentions the "new teal": that's the teal currently being used in the application. Was there a mistake?

**Comment by rmarcalo** [comment]
Hi! Yes, sorry, I got the HEX codes mixed up. The new one is #37D8BC, which should be slightly less green.

**Comment by ColinEberhardt** [comment]
I think this epic has now been split into separate issues, so I am now closing.
