### ISSUE TITLE
Improve the GH Pages deployment

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#696]
- [ ] Currently based off of a field in `package.json`, which is causing merge conflicts between `dev` and `master`. Perhaps push to a folder with the name `$TRAVIS_BRANCH` instead of what's in the `package.json` file?
- [ ] Each app.json points to the develop folder, instead of their own folders.

**Comment by owennw** [comment]
How will this play with #680?

**Comment by WPFerg** [comment]
It would close it as editing `type` would no longer be needed.

**Comment by WPFerg** [comment]
Closed by #702
