### ISSUE TITLE
Download of our zip causes warnings

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#709]
Currently our zip file causes content warnings (in chrome), on discussion with OpenFin this is likely due to blacklisting of github.io based on other content hosted there.

On the OpenFin demo page we will link to the generator URL:

https://dl.openfin.co/services/download?fileName=StockFlux-master&config=http://scottlogic.github.io/StockFlux/master/app.json

We should probably link to that ourselves also - and remove the download step from the build

**Comment by WPFerg** [comment]
Fixed by #711
