### ISSUE TITLE
Fix gh-pages version update to prevent dev and master build overwrites

### ISSUE THREAD

**Issue by mic-smith** [ScottLogic/StockFlux#713]
Currently deploy.sh is generating the version directory based on the package.json for both dev and master. It does not distinguish between them so it can overwrite when they are set to the same version.

We need a prevent dev builds overwriting an existing master version. Possible options:
- Prefix dev versions
- Add a process to bump dev to the next snapshot version as part of release
- Don't build version directory on dev build.

**Comment by WPFerg** [comment]
My choice of these would probably be don't build version on dev, instead of prefix dev versions. Having the conflicts from the original builder between dev and master wasn't ideal (ie `type` in package.json), so having them minimal would be good.
