### ISSUE TITLE
Scroll snapping?

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/StockFlux#720]
Basically we can set up the scroll in favourites and search such that it snaps to the height of a tile, thus never displaying a partial tile at the top.

This is easy to achieve with the scrollbar we're using, but it depends on whether this is considered a worthwhile enhancement.

**Comment by rmarcalo** [comment]
I think there wouldn't be a usability benefit to this, as the tile on top has no more importance than others. It would probably be a potential source of disorientation, or irritation. Snapped scrolling is usually just used to refocus the view on something which has a firm ideal viewpoint, which I don't believe is the case here.
