### ISSUE TITLE
Bottom stock cut off in compact

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#722]
![image](https://cloud.githubusercontent.com/assets/7962948/13958304/7a9865e0-f047-11e5-84c9-b857a5207efa.png)
I suspect it's because of the `@height: inherit` part of the mixin in `sidebar-compact.less` -- change it to just `width: 100%`, so the scroll bar continues all the way over the search expansion box?

**Comment by ColinEberhardt** [comment]
Should the compact view have a height that is a multiple of the tiles heights so that it only shows whole tiles?

**Comment by WPFerg** [comment]
Probably, though I'd say it'd be another issue. What do you think, @rmarcalo?

**Comment by owennw** [comment]
This is quite related to #721 as the height of the favourite card is changing there.

**Comment by ColinEberhardt** [comment]
Also related to #720 - if the height was a multiple of 'n' tiles, and snapped, it would feel quite nice! Should probably consider these issue together rather than in isolation.

**Comment by WPFerg** [comment]
I'll hold off on my PR for now, then, if it's going to change.

**Comment by rmarcalo** [comment]
In compact view the intention was that the height adapts to the number of cards, as Colin mentioned, so that they are all visible at a glance.

**Comment by ColinEberhardt** [comment]
Thanks @rmarcalo - sounds like we need to tackle a few of these together in order to achieve the required behaviour. For now this is probably a candidate to move into 10.2

**Comment by WPFerg** [comment]
I agree, it was originally intended as a small fix for part of the less refactor that went in for 10.1, but it's probably better to tackle this all in one go (and hopefully once and for all).

**Comment by akhmorgan** [comment]
This issue is linked to and might be resolved through [#381](https://github.com/ScottLogic/StockFlux/issues/381).

**Comment by jdhodges** [comment]
Can't reproduce
