### ISSUE TITLE
When you have one tab in a window, you should be able to drag it to another window

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/StockFlux#726]
Dragging the last/only tab from one window to another window should be possible.
Unsure if you should then destroy the empty window or if it should sit there empty?

**Comment by owennw** [comment]
How do we want this to work?

In Chrome with a single tab the entire window moves until it is dragged into the tab-bar where the whole window collapses to another tab (before releasing moving the mouse out of the tab-bar restores the window again).

Do we want to have the normal interaction, but only when the card is torn in the old window closes? Or the entire window moves? Or when the last card is torn out the old window shrinks/closes (what if the user changes their mind?)

@rmarcalo

**Comment by rmarcalo** [comment]
My ideal for this was the following (and it might me way too complex):

A few seconds (1-2) after you detach and move a card away the entire window disappears. As the cursor moves around only the card is shown. When the card stops moving (after 1-2 seconds) the window appears again, aligning perfectly to the position of the card. At this point, if the user releases the card the window is placed. If moves again the window is hidden again. If the card is dragged into another window then it starts to belong there. The same would happen for compact view.

If this is too complicated:

A few seconds (1-2) after you detach and move a card away the entire window disappears. As the cursor moves around only the card is shown. It only reappears again if the card is dropped (without being included into another window).

**Comment by owennw** [comment]
It's good to know the ideal, I think we an aim for that and see how it goes!
