### ISSUE TITLE
Close button for search is mis-alligned in compact mode with the main close button

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/StockFlux#728]
![crossallignment](https://cloud.githubusercontent.com/assets/5921987/13981469/3008b8a0-f0dc-11e5-909d-41c8bb51d6ca.png)

I think this might look neater if the two close buttons were alligned

**Comment by chriswilty** [comment]
👍 This looks like an easy-win.

**Comment by AndySmithSL** [comment]
Fix completed, closing issue.
