### ISSUE TITLE
Travis intermittently fails

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#732]
Travis now seems to periodically fail for PhantomJS downloading (use a Bitflux bundle?)

```

> phantomjs-prebuilt@2.1.4 install /home/travis/build/ScottLogic/StockFlux/node_modules/BitFlux/node_modules/phantomjs-prebuilt
> node install.js
Found PhantomJS at /usr/local/phantomjs/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 1.9.8 @ /usr/local/phantomjs/bin/phantomjs.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/2.14.2 node/v4.0.0 linux x64"
  },
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "A7CB1D0FB7589B38",
  "x-amz-id-2": "fDCqVbiB7y8xrtemqhgk2uS+UDJROYUTQUSA6J5IyaXdFjOJFos3whSNatOB+qM8LGyueTy4m+0=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Wed, 23 Mar 2016 12:45:54 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.
If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
> phantomjs@1.9.19 install /home/travis/build/ScottLogic/StockFlux/node_modules/BitFlux/node_modules/grunt-svg-sprite/node_modules/svg-sprite/node_modules/phantomjs
> node install.js
Found PhantomJS at /usr/local/phantomjs/bin/phantomjs ...verifying
Writing location.js file
PhantomJS is already installed on PATH at /usr/local/phantomjs/bin/phantomjs
npm WARN engine agentkeepalive@0.2.4: wanted: {"node":"0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.0.0/bin/node" "/home/travis/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! phantomjs-prebuilt@2.1.4 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.4 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/ScottLogic/StockFlux/npm-debug.log
```

**Comment by WPFerg** [comment]
Looks like it's bitbucket, but there's a workaround [here](https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs)

I'll push up a PR that could hopefully fix this

**Comment by jleft** [comment]
BitFlux has a development dependency on PhantomJS 2.x.x - this is not pre-installed on Travis, so it has to be downloaded and installed on every build, which is slow and unreliable. This dependency will be removed in the next BitFlux release (latest release is currently 1.5.0).

As a short-term solution, I've [created a branch](https://github.com/ScottLogic/BitFlux/commits/1.3.0-remove-phantom-js-2-dependency) at ScottLogic/BitFlux which includes the version of BitFlux currently being used in StockFlux, but with PhantomJS 2.x.x removed.

PhantomJS 2.x.x was only used to run unit tests, and as StockFlux doesn't run BitFlux's unit tests, this change should have no consequence for StockFlux.

Reverting #744 and updating the BitFlux depdendency to `ScottLogic/BitFlux#37e9a2d632a0ff06e5fc3932bcbd9400bcfabb5d` should result in more reliable builds.

**Comment by mic-smith** [comment]
@jleft Thanks :)

**Comment by mic-smith** [comment]
Have updated dependency

**Comment by jleft** [comment]
This is different to the original observation but FWIW, BitFlux was erroring fairly frequently on Travis during `npm install` with `ECONNRESET` errors.

It seems like updating Travis to run on Node >= 4.4.x has solved it (not 100% sure that this is the fix, as the cause appears to be a transient network issue, but it's to be doing the job for me and others!).

Unless there's a reason to run on Node 4.0.x instead of Node 4.4.x, then I'd suggest updating Travis.

**Comment by mic-smith** [comment]
Thanks @jleft  
Will merge as we have no specific version requirements that I know of.
