### ISSUE TITLE
In compact view, bottom stock "bottom" is visible beneath search bar

### ISSUE THREAD

**Issue by jackarnstein** [ScottLogic/StockFlux#737]
![image](https://cloud.githubusercontent.com/assets/5921987/13986306/a3a31e46-f0f9-11e5-810a-24d6138865a3.png)

Just the one pixel width, but you can see the bottom of the bottom stock under the search bar

**Comment by WPFerg** [comment]
This might also be related to #722 where the bottom stock is cut off in compact view when scrolling to the bottom. Reducing the size of the scrollable area would fix this, too
