### ISSUE TITLE
Consider adding a gradient fill to the area chart

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#745]

**Comment by jleft** [comment]
This is included in [BitFlux 1.6.0](https://github.com/ScottLogic/BitFlux/releases/tag/1.6.0).

For now, the area series does not have an outline stroke; this is something which we could include in a subsequent release.

**Comment by mic-smith** [comment]
Thanks @jleft. Updated dev to 1.6. Looks good
