### ISSUE TITLE
It's possible to tear in to a window that is currently behind other windows

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/StockFlux#770]
This seems a little bit weird.

Steps to reproduce:
1. create 2 windows
2. put an application in front of just one of the windows (let's call that window B). So we have one window still visible, window A, and one window which is now hidden behind some other app, window B.
3. Drag a favourite from the displayed window, window A, over to where window B would be if it were not hidden behind another application. Specifically aim for where the sidebar would be.
4. Release the tearout.

Observed behaviour:
Instead of getting a new window, the tearout will snap into window B and bring it to the front of the desktop.

I'm not sure what the desired behaviour is here exactly, but I think that if I were to release a tearout, seemingly not over any other StockFlux windows, then I would expect a new window to be created.

**Comment by akhmorgan** [comment]
[StockFlux_Issue_770.zip](https://github.com/ScottLogic/StockFlux/files/210305/StockFlux_Issue_770.zip)

**Comment by msuperina** [comment]
Solved by #809
