### ISSUE TITLE
Swap chart title and menu position

### ISSUE THREAD

**Issue by mic-smith** [ScottLogic/StockFlux#779]
From #666

**Comment by mic-smith** [comment]
@rmarcalo Should the logo text now be moved to be in line with the chart title? For example:

Current alignment:
![image](https://cloud.githubusercontent.com/assets/17762186/14639824/7c8704f6-0636-11e6-8839-a575a9aeb893.png)

Aligned:
![image](https://cloud.githubusercontent.com/assets/17762186/14639832/8309a41e-0636-11e6-8cd7-242df83b8895.png)

**Comment by rmarcalo** [comment]
Yes, I think it looks more balanced that way!
