### ISSUE TITLE
Duplicate favourites list

### ISSUE THREAD

**Issue by nwolverson** [ScottLogic/StockFlux#930]
After searching and deleting search it is possible to get into a situation where the favourites list is repeated multiple times

![image](https://cloud.githubusercontent.com/assets/2770891/21021921/98fdf8a8-bd72-11e6-9547-df65aaa30967.png)

I can reproduce this fairly often (but not always) by repeatedly hitting "m" and "delete" alternately, in this instance. Presumably issue with an in-flight asynchronous request.

**Comment by msuperina** [comment]
I cannot reproduce this issue, neither when I install the app nor in local development.
