### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by harrymt** [ScottLogic/StockFlux#956]
Is there a live demo for this? Perhaps link it in README.md or in GitHubs website box?

**Comment by jleft** [comment]
Hi @harrymt - yes, there's a live demo of the application available to download. There's a link in the README, under the _[Installing](https://github.com/ScottLogic/StockFlux#installing)_ section. StockFlux is also listed on [OpenFin's Demo](https://openfin.co/demos/) page.

**Comment by msuperina** [comment]
Closing as solved
