### ISSUE TITLE
Investigate different processing models

### ISSUE THREAD

**Issue by msuperina** [ScottLogic/StockFlux#969]
Currently the app uses a parent / children model.
It is worth investigating different models (e.g. windows in same process vs. different processes) and that could be an idea for a blog post.

**Comment by ColinEberhardt** [comment]
@owennw was looking into this

**Comment by markjose** [comment]
The application is currently being separated in to 3 seperate apps, Search, WatchList and Chart to demonstrate the InterAppBus effectivily. Closed this as it's no redundant.
