### ISSUE TITLE
Dates are shown incorrectly on x-axis

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/StockFlux#992]
Date tick labels are incorrectly / inconsistently displayed. This seems to be a [BitFlux](https://github.com/ScottLogic/BitFlux) issue, rather than a StockFlux issue, however, that repo seems like it's dormant.

StockFlux Version 12.0.1

![image](https://user-images.githubusercontent.com/15246391/49366769-12029100-f6e2-11e8-879c-7c5696797891.png)

As you can see, some ticks have a Month name, others have what looks like "Day Date".

**Comment by chriswilty** [comment]
This might already be fixed in BitFlux; we are not using the [latest version](https://github.com/ScottLogic/BitFlux/releases).

**Comment by JackG188** [comment]
Can't reproduce
