### ISSUE TITLE
Investigate possibility to prevent window being dragged outside of screen

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/StockFlux#994]
Currently, there is nothing to prevent a window being dragged off-screen. This is also the case with standard windows at least in Windows 10. Is there a case to be made for preventing this behaviour, to prevent (in the extreme case) windows being unrecoverable? e.g.

- Dock a small window to the base of a large window.
- Drag the small window upwards until the toolbar of the large window is off-screen.
- Undock the small window by clicking the padlock icon.
=> Large window can no longer be moved or controlled using the toolbar controls
(note that in the below images, the top of the image is the top of the screen)

![window_whoops_1](https://user-images.githubusercontent.com/15246391/49386145-d930df00-f716-11e8-9fea-a326252ae9c0.png)

- Now dock the small window to the large one again, this time snapping it to the top of the large window.
=> Neither window can be moved or controlled! Closing and re-opening just re-opens them in the same predicament

![window_whoops_2](https://user-images.githubusercontent.com/15246391/49385896-4b54f400-f716-11e8-9535-361718748d87.png)

- Recovery is possible by pulling out another stock into its own window, docking that to the other windows, and pulling them back into the screen.

**Comment by chriswilty** [comment]
Possible solutions could be discussed with OpenFin team; one problem that @msuperina pointed out with preventing a window from going out-of-bounds is that _programatically_ changing a window's bounds automatically undocks any windows docked to it. It would be nice if we had the ability to cancel any window move event that would push the window out-of-bounds.

**Comment by markjose** [comment]
This is an issue with the OpenFin layouts API. It makes sense to raise this with the FINOS Hadouken layouts Working Group, but it is not in the scope of this repo, hence closing it.
